services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    network_mode: host
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - LLM_MODEL=${LLM_MODEL}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint:
      - /bin/sh
      - -c
      - |
        # Stop script on error
        set -e

        # --- START SERVER ---
        echo 'Starting server...'
        ollama serve &
        PID=$$!

        # Wait until server responds
        echo 'Waiting for Ollama API...'
        while ! ollama list > /dev/null 2>&1; do
            sleep 1
        done
        # --- START SERVER END ---

        # --- TRY PULLING 5 TIMES ---
        echo "Pulling model: ${LLM_MODEL}..."
        n=0
        until [ "$$n" -ge 5 ]
        do
           echo "Attempt $((n+1))/5 to pull model..."
           ollama pull ${LLM_MODEL} && break
           n=$$(($$n+1))
           echo "Pull failed. Retrying in 10 seconds..."
           sleep 10
        done
        
        # Check if failed
        if [ "$$n" -eq 5 ]; then
           echo "Failed to pull model after 5 attempts."
           exit 1
        fi
        # --- TRY PULLING 5 TIMES END ---

        # --- LOAD MODEL ---
        echo 'Loading model into memory...'
        echo 'no think, dot' | ollama run ${LLM_MODEL} > /dev/null
        
        # Report success
        echo 'Model loaded successfully!'
        wait $$PID
        # --- LOAD MODEL END ---

volumes:
  ollama-data:
