services:
  ollama:
    image: docker.io/ollama/ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - /etc/tg-llm-multibot/ollama-entrypoint.sh:usr/local/bin/entrypoint.sh:ro
      - ~/.local/share/ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_MODEL
      - OLLAMA_KV_CACHE_TYPE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
    healthcheck:  # 1 hour of checking
      test: ["CMD-SHELL", "ollama ps | grep -q $OLLAMA_MODEL"]
      interval: 10s
      retries: 360

volumes:
  ollama-data:
