services:
  tg-handler:
    image: docker.io/veotri/tg-handler:v0.5.1
    build:
      context: ..
      dockerfile: tg-handler/Dockerfile
    environment:
      - API_KEYS_FILE=/run/secrets/api_keys
      - OLLAMA_MODEL
      - OLLAMA_API_URL
    volumes:
      - ../confs:/app/confs:ro
      - ../history:/app/history 
    secrets:
      - api_keys
    restart: always

secrets:
  api_keys:
    file: ../api_keys.txt
