services:
  ollama:
    image: docker.io/ollama/ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/.config/telellama/ollama-entrypoint.sh:usr/local/bin/entrypoint.sh:ro,Z
      - ${HOME}/.local/share/ollama-data:/root/.ollama:Z
    environment:
      - OLLAMA_HOST
      - OLLAMA_MODEL
      - OLLAMA_KV_CACHE_TYPE
      - OLLAMA_KEEP_ALIVE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "ollama ps | grep -q $OLLAMA_MODEL"]
      interval: 10s
      retries: 360

volumes:
  ollama-data:
