services:
  tg-handler:
    image: docker.io/veotri/tg-handler:local
    restart: always
    build:
      context: ..
      dockerfile: tg-handler/Dockerfile
    environment:
      - API_KEYS_FILE=/run/secrets/api_keys
      - OLLAMA_MODEL
      - OLLAMA_API_URL
    volumes:
      - /etc/tg-llm-multibot/confs:/app/confs:ro
      - ~/.local/share/tg-data/history:/app/history 
    secrets:
      - api_keys

secrets:
  api_keys:
    file: /etc/tg-llm-multibot/api_keys.txt
